### ISSUE TITLE
Clauses do not have access to outer scopes

### ISSUE THREAD

**Issue by rbaltrusch** [rbaltrusch/python_interpreter#4]
Inner scopes do not have access to variables defined in outer scopes. This makes it impossible to access global variables, define closures or even call a function inside another function defined elsewhere, e.g.
```
define function a as {
    print 1
}

define function b as {
    #this will fail because it doesnt have access to outer scope
    call a
}
```

To reproduce this example, run the following code, which assigns 1 to a global variable b, then tries to access this variable b to print it inside an inner scope.
```
set b to 1
set a to {print b} and call it
```
The example above results in the following exception:

```diff
Traceback (most recent call last):

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\main.py", line 25, in <module>
!    inter.interpret(syntax_block)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\interpreter.py", line 26, in interpret
!    raise e

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\interpreter.py", line 23, in interpret
!    token.run(self)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\token_.py", line 75, in run
!    function(interpreter)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\tokens.py", line 188, in _run
!    function.get_value()(interpreter)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\tokens.py", line 164, in run_tokens
!    token.run(interpreter)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\token_.py", line 75, in run
!    function(interpreter)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\tokens.py", line 73, in _run
!    print(value.get_value())

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\token_.py", line 152, in get_value
!    raise exceptions.UndefinedVariableException(self)

- UndefinedVariableException: Line 2: Tried to access undefined variable b!
```

Tested with Python 3.8.3, Win10.

**Comment by rbaltrusch** [comment]
Fixed with commit [1e4ea23](https://github.com/rbaltrusch/python_interpreter/commit/1e4ea23cb617b413503f00105578047c8f3e0527).
