### ISSUE TITLE
Float values are not parsed properly

### ISSUE THREAD

**Issue by rbaltrusch** [rbaltrusch/python_interpreter#8]
Float values in the example script example2.nat are not parsed properly, as source code strings, such as "1.5", are preprocessed by the lexer and split into three parts ("1", ".", "5"), which then cannot be recognized as a proper float value. As a result the script fails, as it contains an unexpected token (".").

**To Reproduce**
1. Run example2.nat
2. See error:

```diff
Traceback (most recent call last):

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\main.py", line 23, in <module>
!    tokens = list(lex.lex(file_contents))

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\lexer.py", line 16, in lex
!    token = self.token_factory.create_token(s)

  File "D:\Alle_Dateien\Code\Python\NatScript Interpreter\interpreter\token_.py", line 35, in create_token
-    raise exceptions.LexError(token, self.line_number)

LexError: Line 8: . was not expected at this time!
```

**Expected behavior**
Float values shouldnt be split by the preprocessing logic in the Lexer.

Occurs on main branch (commit 60a8bf9).

The bug should be caused by commit 96b824823fcdd173e8d6f2a4ecb4a2241c41c9ce.

**Comment by rbaltrusch** [comment]
Fixed in commit 119c031.
